// Generated by the painted-wardrobe build (see assets/painted/README.md). Don't edit by hand.
// bounds: where each piece sits in the 200 × 320 doll box (x, y, width, height); color: its main color.

export const PAINTED_MANIFEST: { id: string; slot: string; name: string; color: string; bounds: [number, number, number, number] }[] = [
  { id: 'pd-party', slot: 'dress', name: 'Party dress', color: '#b23a3a', bounds: [38.1, 116.3, 123.1, 148.2] },
  { id: 'pd-blue-gown', slot: 'dress', name: 'Ball gown', color: '#8cbfe0', bounds: [9.8, 117, 179.7, 189] },
  { id: 'pd-pink-gown', slot: 'dress', name: 'Princess gown', color: '#eb9fb0', bounds: [1.9, 115.3, 195.4, 196.2] },
  { id: 'pd-sundress', slot: 'dress', name: 'Sundress', color: '#ecc581', bounds: [58.5, 117, 82.3, 141] },
  { id: 'pt-tee', slot: 'top', name: 'T-shirt', color: '#5ebfe1', bounds: [62.8, 116, 73.4, 71.9] },
  { id: 'pt-hoodie', slot: 'top', name: 'Hoodie', color: '#b190c0', bounds: [52.4, 106.7, 94.5, 90.9] },
  { id: 'pb-jeans', slot: 'bottom', name: 'Jeans', color: '#536e8d', bounds: [68.9, 182.6, 61.2, 112.8] },
  { id: 'pb-skirt', slot: 'bottom', name: 'Skirt', color: '#e99db1', bounds: [52.4, 182.6, 94.9, 81.6] },
  { id: 'ps-sneakers', slot: 'shoes', name: 'Sneakers', color: '#996569', bounds: [81, 284.9, 36.9, 25.8] },
  { id: 'ps-flats', slot: 'shoes', name: 'Party shoes', color: '#9e659e', bounds: [81.4, 288.1, 36.2, 23.3] },
  { id: 'ps-boots', slot: 'shoes', name: 'Boots', color: '#6a3e31', bounds: [80, 279.2, 39, 34] },
  { id: 'ph-crown', slot: 'hat', name: 'Crown', color: '#c88b57', bounds: [68.9, 1.4, 61.9, 33.3] },
  { id: 'ph-long', slot: 'hair', name: 'Long hair', color: '#d39f67', bounds: [29.8, 9.7, 139.6, 184] },
  { id: 'ph-ponytail', slot: 'hair', name: 'Ponytail', color: '#d5a16b', bounds: [50.6, 2.1, 129.6, 219.1] },
  { id: 'ph-buns', slot: 'hair', name: 'Two buns', color: '#d39c5b', bounds: [30.9, 6.8, 137.1, 100.6] },
  { id: 'ph-curly', slot: 'hair', name: 'Curly puff', color: '#dca863', bounds: [31.6, 0.4, 135.7, 112.4] },
  { id: 'ph-bob', slot: 'hair', name: 'Short bob', color: '#d39f5e', bounds: [40.9, 10, 117, 107] },
  { id: 'ph-braid', slot: 'hair', name: 'Side braid', color: '#c8945e', bounds: [30.2, 9.7, 139.2, 189.4] },
  { id: 'pb-shorts', slot: 'bottom', name: 'Shorts', color: '#6a82a0', bounds: [65.3, 182.6, 68.7, 66.2] },
];
