// node gen-data.cjs <out dir with manifest.json> <repo root>  -> copies PNGs, writes painted-data.ts
const fs=require('fs'),path=require('path');
const [,,out,root]=process.argv;
const man=JSON.parse(fs.readFileSync(path.join(out,'manifest.json'),'utf8'));
const dest=path.join(root,'src/aria/assets/painted');fs.mkdirSync(dest,{recursive:true});
for(const m of man)fs.copyFileSync(path.join(out,m.id+'.png'),path.join(dest,m.id+'.png'));
const rows=man.map(m=>`  { id: '${m.id}', slot: '${m.slot}', name: '${m.name}', color: '${m.color}', bounds: [${m.bounds.join(', ')}] },`).join('\n');
fs.writeFileSync(path.join(root,'src/aria/dress/painted-data.ts'),`// Generated by the painted-wardrobe build (see assets/painted/README.md). Don't edit by hand.
// bounds: where each piece sits in the 200 × 320 doll box (x, y, width, height); color: its main color.

export const PAINTED_MANIFEST: { id: string; slot: string; name: string; color: string; bounds: [number, number, number, number] }[] = [
${rows}
];
`);
console.log('wrote',man.length,'items');
